### ISSUE TITLE
Use same version for each crate

### ISSUE THREAD

**Issue by AZProductions** [Avdan-OS/AvdanOS#301]
```toml
[package]
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
```
