### ISSUE TITLE
Use glob path instead of defining each package

### ISSUE THREAD

**Issue by AZProductions** [Avdan-OS/AvdanOS#483]
Instead of defining each package individually, we should rather be using a glob path. Currently we are manually defining each package in `./Cargo.toml`.
```toml
[workspace]
members = [
    "crates/toybox_c1200",
    ...
]
resolver = "2"
```
By using a glob path, we can cut down on the lines code needed.
```toml
[workspace]
members = ["crates/*"]
```
