### ISSUE TITLE
Single build alias for all plugins

### ISSUE THREAD

**Issue by AZProductions** [Avdan-OS/AvdanOS#490]
We should provide an alias that builds and bundles all plugins at once using the alias field in `.cargo/config.toml`.

```toml
[alias]
ci = "run --package xtask --release -- -p 1 2 3 ..."
```

Running `cargo ci` would then be the only step needed for building it locally.
